"""create foreignkey Task_Priority

Revision ID: 0c9736c7831c
Revises: d5297bd664a3
Create Date: 2023-10-07 10:01:51.088906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9736c7831c'
down_revision = 'd5297bd664a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_task_priority', 'priority', ['priority_id'], ['priority_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_priority', type_='foreignkey')
        batch_op.drop_column('priority_id')

    # ### end Alembic commands ###
