"""1

Revision ID: 2f7bec022603
Revises: 5d60942b32f9
Create Date: 2023-10-23 19:07:33.464304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7bec022603'
down_revision = '5d60942b32f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_project', type_='foreignkey')
        batch_op.create_foreign_key('fk_task_project', 'project', ['project_id'], ['project_id'], ondelete='SET DEFAULT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_project', type_='foreignkey')
        batch_op.create_foreign_key('fk_task_project', 'project', ['project_id'], ['project_id'], ondelete='SET NULL')

    # ### end Alembic commands ###
