"""update_2

Revision ID: e5aa46bc21e8
Revises: e80c254a451d
Create Date: 2023-10-23 18:47:44.335083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5aa46bc21e8'
down_revision = 'e80c254a451d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_project', type_='foreignkey')
        batch_op.create_foreign_key('fk_task_project', 'project', ['project_id'], ['project_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_project', type_='foreignkey')
        batch_op.create_foreign_key('fk_task_project', 'project', ['project_id'], ['project_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
