"""update_2

Revision ID: e80c254a451d
Revises: 9421071a6c0c
Create Date: 2023-10-23 17:43:35.334292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80c254a451d'
down_revision = '9421071a6c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_project', type_='foreignkey')
        batch_op.create_foreign_key('fk_task_project', 'project', ['project_id'], ['project_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_project', type_='foreignkey')
        batch_op.create_foreign_key('fk_task_project', 'project', ['project_id'], ['project_id'])

    # ### end Alembic commands ###
